// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/saga/v1/saga.proto

package sagav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartOrderSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=bookingId,proto3" json:"bookingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderSagaRequest) Reset() {
	*x = StartOrderSagaRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderSagaRequest) ProtoMessage() {}

func (x *StartOrderSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderSagaRequest.ProtoReflect.Descriptor instead.
func (*StartOrderSagaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

func (x *StartOrderSagaRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type StartOrderSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderSagaResponse) Reset() {
	*x = StartOrderSagaResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderSagaResponse) ProtoMessage() {}

func (x *StartOrderSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderSagaResponse.ProtoReflect.Descriptor instead.
func (*StartOrderSagaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

func (x *StartOrderSagaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartOrderSagaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_saga_v1_saga_proto protoreflect.FileDescriptor

const file_proto_saga_v1_saga_proto_rawDesc = "" +
	"\n" +
	"\x18proto/saga/v1/saga.proto\x12\asaga.v1\"5\n" +
	"\x15StartOrderSagaRequest\x12\x1c\n" +
	"\tbookingId\x18\x01 \x01(\tR\tbookingId\"J\n" +
	"\x16StartOrderSagaResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2l\n" +
	"\x17SagaOrchestratorService\x12Q\n" +
	"\x0eStartOrderSaga\x12\x1e.saga.v1.StartOrderSagaRequest\x1a\x1f.saga.v1.StartOrderSagaResponseB/Z-github.com/ticketbox/pkg/proto/saga/v1;sagav1b\x06proto3"

var (
	file_proto_saga_v1_saga_proto_rawDescOnce sync.Once
	file_proto_saga_v1_saga_proto_rawDescData []byte
)

func file_proto_saga_v1_saga_proto_rawDescGZIP() []byte {
	file_proto_saga_v1_saga_proto_rawDescOnce.Do(func() {
		file_proto_saga_v1_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_saga_v1_saga_proto_rawDesc), len(file_proto_saga_v1_saga_proto_rawDesc)))
	})
	return file_proto_saga_v1_saga_proto_rawDescData
}

var file_proto_saga_v1_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_saga_v1_saga_proto_goTypes = []any{
	(*StartOrderSagaRequest)(nil),  // 0: saga.v1.StartOrderSagaRequest
	(*StartOrderSagaResponse)(nil), // 1: saga.v1.StartOrderSagaResponse
}
var file_proto_saga_v1_saga_proto_depIdxs = []int32{
	0, // 0: saga.v1.SagaOrchestratorService.StartOrderSaga:input_type -> saga.v1.StartOrderSagaRequest
	1, // 1: saga.v1.SagaOrchestratorService.StartOrderSaga:output_type -> saga.v1.StartOrderSagaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_saga_v1_saga_proto_init() }
func file_proto_saga_v1_saga_proto_init() {
	if File_proto_saga_v1_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_saga_v1_saga_proto_rawDesc), len(file_proto_saga_v1_saga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_saga_v1_saga_proto_goTypes,
		DependencyIndexes: file_proto_saga_v1_saga_proto_depIdxs,
		MessageInfos:      file_proto_saga_v1_saga_proto_msgTypes,
	}.Build()
	File_proto_saga_v1_saga_proto = out.File
	file_proto_saga_v1_saga_proto_goTypes = nil
	file_proto_saga_v1_saga_proto_depIdxs = nil
}
