// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/saga/v1/saga.proto

package sagav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaOrchestratorService_StartOrderSaga_FullMethodName = "/saga.v1.SagaOrchestratorService/StartOrderSaga"
)

// SagaOrchestratorServiceClient is the client API for SagaOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaOrchestratorServiceClient interface {
	StartOrderSaga(ctx context.Context, in *StartOrderSagaRequest, opts ...grpc.CallOption) (*StartOrderSagaResponse, error)
}

type sagaOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaOrchestratorServiceClient(cc grpc.ClientConnInterface) SagaOrchestratorServiceClient {
	return &sagaOrchestratorServiceClient{cc}
}

func (c *sagaOrchestratorServiceClient) StartOrderSaga(ctx context.Context, in *StartOrderSagaRequest, opts ...grpc.CallOption) (*StartOrderSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOrderSagaResponse)
	err := c.cc.Invoke(ctx, SagaOrchestratorService_StartOrderSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaOrchestratorServiceServer is the server API for SagaOrchestratorService service.
// All implementations must embed UnimplementedSagaOrchestratorServiceServer
// for forward compatibility.
type SagaOrchestratorServiceServer interface {
	StartOrderSaga(context.Context, *StartOrderSagaRequest) (*StartOrderSagaResponse, error)
	mustEmbedUnimplementedSagaOrchestratorServiceServer()
}

// UnimplementedSagaOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaOrchestratorServiceServer struct{}

func (UnimplementedSagaOrchestratorServiceServer) StartOrderSaga(context.Context, *StartOrderSagaRequest) (*StartOrderSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOrderSaga not implemented")
}
func (UnimplementedSagaOrchestratorServiceServer) mustEmbedUnimplementedSagaOrchestratorServiceServer() {
}
func (UnimplementedSagaOrchestratorServiceServer) testEmbeddedByValue() {}

// UnsafeSagaOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaOrchestratorServiceServer will
// result in compilation errors.
type UnsafeSagaOrchestratorServiceServer interface {
	mustEmbedUnimplementedSagaOrchestratorServiceServer()
}

func RegisterSagaOrchestratorServiceServer(s grpc.ServiceRegistrar, srv SagaOrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedSagaOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaOrchestratorService_ServiceDesc, srv)
}

func _SagaOrchestratorService_StartOrderSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOrderSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaOrchestratorServiceServer).StartOrderSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaOrchestratorService_StartOrderSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaOrchestratorServiceServer).StartOrderSaga(ctx, req.(*StartOrderSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaOrchestratorService_ServiceDesc is the grpc.ServiceDesc for SagaOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saga.v1.SagaOrchestratorService",
	HandlerType: (*SagaOrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOrderSaga",
			Handler:    _SagaOrchestratorService_StartOrderSaga_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saga/v1/saga.proto",
}
