// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: booking/v1/booking.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Items         []*BookingItemRequest  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	BookingMode   string                 `protobuf:"bytes,4,opt,name=booking_mode,json=bookingMode,proto3" json:"booking_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateBookingRequest) GetItems() []*BookingItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateBookingRequest) GetBookingMode() string {
	if x != nil {
		return x.BookingMode
	}
	return ""
}

type BookingItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketTierId  string                 `protobuf:"bytes,1,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingItemRequest) Reset() {
	*x = BookingItemRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingItemRequest) ProtoMessage() {}

func (x *BookingItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingItemRequest.ProtoReflect.Descriptor instead.
func (*BookingItemRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *BookingItemRequest) GetTicketTierId() string {
	if x != nil {
		return x.TicketTierId
	}
	return ""
}

func (x *BookingItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ListUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBookingsRequest) Reset() {
	*x = ListUserBookingsRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBookingsRequest) ProtoMessage() {}

func (x *ListUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserBookingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingDetail       `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBookingsResponse) Reset() {
	*x = ListUserBookingsResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBookingsResponse) ProtoMessage() {}

func (x *ListUserBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListUserBookingsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserBookingsResponse) GetBookings() []*BookingDetail {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListUserBookingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookingDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId          string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalAmountCents int64                  `protobuf:"varint,5,opt,name=total_amount_cents,json=totalAmountCents,proto3" json:"total_amount_cents,omitempty"`
	Items            []*BookingItem         `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookingDetail) Reset() {
	*x = BookingDetail{}
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetail) ProtoMessage() {}

func (x *BookingDetail) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetail.ProtoReflect.Descriptor instead.
func (*BookingDetail) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *BookingDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BookingDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingDetail) GetTotalAmountCents() int64 {
	if x != nil {
		return x.TotalAmountCents
	}
	return 0
}

func (x *BookingDetail) GetItems() []*BookingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BookingDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BookingItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketTierId   string                 `protobuf:"bytes,2,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	TierName       string                 `protobuf:"bytes,3,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,5,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingItem) Reset() {
	*x = BookingItem{}
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingItem) ProtoMessage() {}

func (x *BookingItem) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingItem.ProtoReflect.Descriptor instead.
func (*BookingItem) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *BookingItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingItem) GetTicketTierId() string {
	if x != nil {
		return x.TicketTierId
	}
	return ""
}

func (x *BookingItem) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *BookingItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BookingItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

var File_booking_v1_booking_proto protoreflect.FileDescriptor

const file_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18booking/v1/booking.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x124\n" +
	"\x05items\x18\x03 \x03(\v2\x1e.booking.v1.BookingItemRequestR\x05items\x12!\n" +
	"\fbooking_mode\x18\x04 \x01(\tR\vbookingMode\"V\n" +
	"\x12BookingItemRequest\x12$\n" +
	"\x0eticket_tier_id\x18\x01 \x01(\tR\fticketTierId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"c\n" +
	"\x17ListUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"g\n" +
	"\x18ListUserBookingsResponse\x125\n" +
	"\bbookings\x18\x01 \x03(\v2\x19.booking.v1.BookingDetailR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"N\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x83\x02\n" +
	"\rBookingDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12,\n" +
	"\x12total_amount_cents\x18\x05 \x01(\x03R\x10totalAmountCents\x12-\n" +
	"\x05items\x18\x06 \x03(\v2\x17.booking.v1.BookingItemR\x05items\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa6\x01\n" +
	"\vBookingItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eticket_tier_id\x18\x02 \x01(\tR\fticketTierId\x12\x1b\n" +
	"\ttier_name\x18\x03 \x01(\tR\btierName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x05 \x01(\x03R\x0eunitPriceCents2\xd3\x02\n" +
	"\x0eBookingService\x12L\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x19.booking.v1.BookingDetail\x12F\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x19.booking.v1.BookingDetail\x12]\n" +
	"\x10ListUserBookings\x12#.booking.v1.ListUserBookingsRequest\x1a$.booking.v1.ListUserBookingsResponse\x12L\n" +
	"\rCancelBooking\x12 .booking.v1.CancelBookingRequest\x1a\x19.booking.v1.BookingDetailB5Z3github.com/ticketbox/pkg/proto/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_booking_proto_rawDescOnce sync.Once
	file_booking_v1_booking_proto_rawDescData []byte
)

func file_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)))
	})
	return file_booking_v1_booking_proto_rawDescData
}

var file_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_booking_v1_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),     // 0: booking.v1.CreateBookingRequest
	(*BookingItemRequest)(nil),       // 1: booking.v1.BookingItemRequest
	(*GetBookingRequest)(nil),        // 2: booking.v1.GetBookingRequest
	(*ListUserBookingsRequest)(nil),  // 3: booking.v1.ListUserBookingsRequest
	(*ListUserBookingsResponse)(nil), // 4: booking.v1.ListUserBookingsResponse
	(*CancelBookingRequest)(nil),     // 5: booking.v1.CancelBookingRequest
	(*BookingDetail)(nil),            // 6: booking.v1.BookingDetail
	(*BookingItem)(nil),              // 7: booking.v1.BookingItem
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_booking_v1_booking_proto_depIdxs = []int32{
	1, // 0: booking.v1.CreateBookingRequest.items:type_name -> booking.v1.BookingItemRequest
	6, // 1: booking.v1.ListUserBookingsResponse.bookings:type_name -> booking.v1.BookingDetail
	7, // 2: booking.v1.BookingDetail.items:type_name -> booking.v1.BookingItem
	8, // 3: booking.v1.BookingDetail.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	2, // 5: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	3, // 6: booking.v1.BookingService.ListUserBookings:input_type -> booking.v1.ListUserBookingsRequest
	5, // 7: booking.v1.BookingService.CancelBooking:input_type -> booking.v1.CancelBookingRequest
	6, // 8: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.BookingDetail
	6, // 9: booking.v1.BookingService.GetBooking:output_type -> booking.v1.BookingDetail
	4, // 10: booking.v1.BookingService.ListUserBookings:output_type -> booking.v1.ListUserBookingsResponse
	6, // 11: booking.v1.BookingService.CancelBooking:output_type -> booking.v1.BookingDetail
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_proto_init() }
func file_booking_v1_booking_proto_init() {
	if File_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_proto = out.File
	file_booking_v1_booking_proto_goTypes = nil
	file_booking_v1_booking_proto_depIdxs = nil
}
