// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Title         string                     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                     `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Venue         string                     `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	Location      string                     `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Date          *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	ImageUrl      string                     `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Tiers         []*CreateTicketTierRequest `protobuf:"bytes,8,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateEventRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateEventRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateEventRequest) GetTiers() []*CreateTicketTierRequest {
	if x != nil {
		return x.Tiers
	}
	return nil
}

type CreateTicketTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	TotalQuantity int32                  `protobuf:"varint,3,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketTierRequest) Reset() {
	*x = CreateTicketTierRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketTierRequest) ProtoMessage() {}

func (x *CreateTicketTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketTierRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketTierRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketTierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketTierRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *CreateTicketTierRequest) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListEventsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventDetail         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsResponse) GetEvents() []*EventDetail {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEventsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Venue         string                 `protobuf:"bytes,5,opt,name=venue,proto3" json:"venue,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateEventRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *UpdateEventRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{7}
}

type EventDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Venue         string                 `protobuf:"bytes,5,opt,name=venue,proto3" json:"venue,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Tiers         []*TicketTier          `protobuf:"bytes,10,rep,name=tiers,proto3" json:"tiers,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDetail) Reset() {
	*x = EventDetail{}
	mi := &file_proto_event_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetail) ProtoMessage() {}

func (x *EventDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetail.ProtoReflect.Descriptor instead.
func (*EventDetail) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *EventDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventDetail) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *EventDetail) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventDetail) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *EventDetail) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EventDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventDetail) GetTiers() []*TicketTier {
	if x != nil {
		return x.Tiers
	}
	return nil
}

func (x *EventDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TicketTier struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId           string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents        int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	TotalQuantity     int32                  `protobuf:"varint,5,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,6,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Version           int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TicketTier) Reset() {
	*x = TicketTier{}
	mi := &file_proto_event_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTier) ProtoMessage() {}

func (x *TicketTier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTier.ProtoReflect.Descriptor instead.
func (*TicketTier) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *TicketTier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketTier) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketTier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketTier) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *TicketTier) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *TicketTier) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *TicketTier) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetTicketAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TierId        string                 `protobuf:"bytes,1,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketAvailabilityRequest) Reset() {
	*x = GetTicketAvailabilityRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketAvailabilityRequest) ProtoMessage() {}

func (x *GetTicketAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetTicketAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *GetTicketAvailabilityRequest) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

type TicketAvailabilityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TierId            string                 `protobuf:"bytes,1,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Version           int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	PriceCents        int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TicketAvailabilityResponse) Reset() {
	*x = TicketAvailabilityResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketAvailabilityResponse) ProtoMessage() {}

func (x *TicketAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*TicketAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *TicketAvailabilityResponse) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *TicketAvailabilityResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *TicketAvailabilityResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TicketAvailabilityResponse) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

type UpdateTicketAvailabilityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TierId          string                 `protobuf:"bytes,1,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	QuantityDelta   int32                  `protobuf:"varint,2,opt,name=quantity_delta,json=quantityDelta,proto3" json:"quantity_delta,omitempty"`
	ExpectedVersion int32                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Mode            string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTicketAvailabilityRequest) Reset() {
	*x = UpdateTicketAvailabilityRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketAvailabilityRequest) ProtoMessage() {}

func (x *UpdateTicketAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTicketAvailabilityRequest) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *UpdateTicketAvailabilityRequest) GetQuantityDelta() int32 {
	if x != nil {
		return x.QuantityDelta
	}
	return 0
}

func (x *UpdateTicketAvailabilityRequest) GetExpectedVersion() int32 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateTicketAvailabilityRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// Seat selection messages
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId  string                 `protobuf:"bytes,3,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,5,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Position      string                 `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_event_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *Seat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seat) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Seat) GetTicketTierId() string {
	if x != nil {
		return x.TicketTierId
	}
	return ""
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Seat) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Seat) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Seat) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Seat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Seat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId  string                 `protobuf:"bytes,2,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsRequest) Reset() {
	*x = GetSeatsRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsRequest) ProtoMessage() {}

func (x *GetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *GetSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetSeatsRequest) GetTicketTierId() string {
	if x != nil {
		return x.TicketTierId
	}
	return ""
}

type GetSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsResponse) Reset() {
	*x = GetSeatsResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsResponse) ProtoMessage() {}

func (x *GetSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{15}
}

func (x *GetSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type UpdateSeatStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatStatusRequest) Reset() {
	*x = UpdateSeatStatusRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatStatusRequest) ProtoMessage() {}

func (x *UpdateSeatStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateSeatStatusRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *UpdateSeatStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSeatStatusRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type UpdateBatchSeatStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []string               `protobuf:"bytes,1,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatchSeatStatusRequest) Reset() {
	*x = UpdateBatchSeatStatusRequest{}
	mi := &file_proto_event_v1_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatchSeatStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatchSeatStatusRequest) ProtoMessage() {}

func (x *UpdateBatchSeatStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatchSeatStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatchSeatStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateBatchSeatStatusRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *UpdateBatchSeatStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateBatchSeatStatusRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type UpdateSeatStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatStatusResponse) Reset() {
	*x = UpdateSeatStatusResponse{}
	mi := &file_proto_event_v1_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatStatusResponse) ProtoMessage() {}

func (x *UpdateSeatStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_v1_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_v1_event_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateSeatStatusResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

var File_proto_event_v1_event_proto protoreflect.FileDescriptor

const file_proto_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/event/v1/event.proto\x12\bevent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa0\x02\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05venue\x18\x04 \x01(\tR\x05venue\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x127\n" +
	"\x05tiers\x18\b \x03(\v2!.event.v1.CreateTicketTierRequestR\x05tiers\"u\n" +
	"\x17CreateTicketTierRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x03R\n" +
	"priceCents\x12%\n" +
	"\x0etotal_quantity\x18\x03 \x01(\x05R\rtotalQuantity\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"x\n" +
	"\x11ListEventsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8a\x01\n" +
	"\x12ListEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.event.v1.EventDetailR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x82\x02\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05venue\x18\x05 \x01(\tR\x05venue\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\"/\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x15\n" +
	"\x13DeleteEventResponse\"\xef\x02\n" +
	"\vEventDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05venue\x18\x05 \x01(\tR\x05venue\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12*\n" +
	"\x05tiers\x18\n" +
	" \x03(\v2\x14.event.v1.TicketTierR\x05tiers\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdc\x01\n" +
	"\n" +
	"TicketTier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12%\n" +
	"\x0etotal_quantity\x18\x05 \x01(\x05R\rtotalQuantity\x12-\n" +
	"\x12available_quantity\x18\x06 \x01(\x05R\x11availableQuantity\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"7\n" +
	"\x1cGetTicketAvailabilityRequest\x12\x17\n" +
	"\atier_id\x18\x01 \x01(\tR\x06tierId\"\x9f\x01\n" +
	"\x1aTicketAvailabilityResponse\x12\x17\n" +
	"\atier_id\x18\x01 \x01(\tR\x06tierId\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x05R\x11availableQuantity\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\"\xa0\x01\n" +
	"\x1fUpdateTicketAvailabilityRequest\x12\x17\n" +
	"\atier_id\x18\x01 \x01(\tR\x06tierId\x12%\n" +
	"\x0equantity_delta\x18\x02 \x01(\x05R\rquantityDelta\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x05R\x0fexpectedVersion\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\xbb\x02\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x03 \x01(\tR\fticketTierId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x05 \x01(\tR\tbookingId\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12\x1a\n" +
	"\bposition\x18\a \x01(\tR\bposition\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x0fGetSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x02 \x01(\tR\fticketTierId\"8\n" +
	"\x10GetSeatsResponse\x12$\n" +
	"\x05seats\x18\x01 \x03(\v2\x0e.event.v1.SeatR\x05seats\"i\n" +
	"\x17UpdateSeatStatusRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"p\n" +
	"\x1cUpdateBatchSeatStatusRequest\x12\x19\n" +
	"\bseat_ids\x18\x01 \x03(\tR\aseatIds\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\">\n" +
	"\x18UpdateSeatStatusResponse\x12\"\n" +
	"\x04seat\x18\x01 \x01(\v2\x0e.event.v1.SeatR\x04seat2\x88\a\n" +
	"\fEventService\x12B\n" +
	"\vCreateEvent\x12\x1c.event.v1.CreateEventRequest\x1a\x15.event.v1.EventDetail\x12<\n" +
	"\bGetEvent\x12\x19.event.v1.GetEventRequest\x1a\x15.event.v1.EventDetail\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.event.v1.ListEventsRequest\x1a\x1c.event.v1.ListEventsResponse\x12B\n" +
	"\vUpdateEvent\x12\x1c.event.v1.UpdateEventRequest\x1a\x15.event.v1.EventDetail\x12J\n" +
	"\vDeleteEvent\x12\x1c.event.v1.DeleteEventRequest\x1a\x1d.event.v1.DeleteEventResponse\x12e\n" +
	"\x15GetTicketAvailability\x12&.event.v1.GetTicketAvailabilityRequest\x1a$.event.v1.TicketAvailabilityResponse\x12[\n" +
	"\x18UpdateTicketAvailability\x12).event.v1.UpdateTicketAvailabilityRequest\x1a\x14.event.v1.TicketTier\x12b\n" +
	"\x1dUpdateBatchTicketAvailability\x12).event.v1.UpdateTicketAvailabilityRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\bGetSeats\x12\x19.event.v1.GetSeatsRequest\x1a\x1a.event.v1.GetSeatsResponse\x12Y\n" +
	"\x10UpdateSeatStatus\x12!.event.v1.UpdateSeatStatusRequest\x1a\".event.v1.UpdateSeatStatusResponse\x12W\n" +
	"\x15UpdateBatchSeatStatus\x12&.event.v1.UpdateBatchSeatStatusRequest\x1a\x16.google.protobuf.EmptyB1Z/github.com/ticketbox/pkg/proto/event/v1;eventv1b\x06proto3"

var (
	file_proto_event_v1_event_proto_rawDescOnce sync.Once
	file_proto_event_v1_event_proto_rawDescData []byte
)

func file_proto_event_v1_event_proto_rawDescGZIP() []byte {
	file_proto_event_v1_event_proto_rawDescOnce.Do(func() {
		file_proto_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_v1_event_proto_rawDesc), len(file_proto_event_v1_event_proto_rawDesc)))
	})
	return file_proto_event_v1_event_proto_rawDescData
}

var file_proto_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_event_v1_event_proto_goTypes = []any{
	(*CreateEventRequest)(nil),              // 0: event.v1.CreateEventRequest
	(*CreateTicketTierRequest)(nil),         // 1: event.v1.CreateTicketTierRequest
	(*GetEventRequest)(nil),                 // 2: event.v1.GetEventRequest
	(*ListEventsRequest)(nil),               // 3: event.v1.ListEventsRequest
	(*ListEventsResponse)(nil),              // 4: event.v1.ListEventsResponse
	(*UpdateEventRequest)(nil),              // 5: event.v1.UpdateEventRequest
	(*DeleteEventRequest)(nil),              // 6: event.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),             // 7: event.v1.DeleteEventResponse
	(*EventDetail)(nil),                     // 8: event.v1.EventDetail
	(*TicketTier)(nil),                      // 9: event.v1.TicketTier
	(*GetTicketAvailabilityRequest)(nil),    // 10: event.v1.GetTicketAvailabilityRequest
	(*TicketAvailabilityResponse)(nil),      // 11: event.v1.TicketAvailabilityResponse
	(*UpdateTicketAvailabilityRequest)(nil), // 12: event.v1.UpdateTicketAvailabilityRequest
	(*Seat)(nil),                            // 13: event.v1.Seat
	(*GetSeatsRequest)(nil),                 // 14: event.v1.GetSeatsRequest
	(*GetSeatsResponse)(nil),                // 15: event.v1.GetSeatsResponse
	(*UpdateSeatStatusRequest)(nil),         // 16: event.v1.UpdateSeatStatusRequest
	(*UpdateBatchSeatStatusRequest)(nil),    // 17: event.v1.UpdateBatchSeatStatusRequest
	(*UpdateSeatStatusResponse)(nil),        // 18: event.v1.UpdateSeatStatusResponse
	(*timestamppb.Timestamp)(nil),           // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 20: google.protobuf.Empty
}
var file_proto_event_v1_event_proto_depIdxs = []int32{
	19, // 0: event.v1.CreateEventRequest.date:type_name -> google.protobuf.Timestamp
	1,  // 1: event.v1.CreateEventRequest.tiers:type_name -> event.v1.CreateTicketTierRequest
	8,  // 2: event.v1.ListEventsResponse.events:type_name -> event.v1.EventDetail
	19, // 3: event.v1.UpdateEventRequest.date:type_name -> google.protobuf.Timestamp
	19, // 4: event.v1.EventDetail.date:type_name -> google.protobuf.Timestamp
	9,  // 5: event.v1.EventDetail.tiers:type_name -> event.v1.TicketTier
	19, // 6: event.v1.EventDetail.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: event.v1.Seat.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: event.v1.Seat.updated_at:type_name -> google.protobuf.Timestamp
	13, // 9: event.v1.GetSeatsResponse.seats:type_name -> event.v1.Seat
	13, // 10: event.v1.UpdateSeatStatusResponse.seat:type_name -> event.v1.Seat
	0,  // 11: event.v1.EventService.CreateEvent:input_type -> event.v1.CreateEventRequest
	2,  // 12: event.v1.EventService.GetEvent:input_type -> event.v1.GetEventRequest
	3,  // 13: event.v1.EventService.ListEvents:input_type -> event.v1.ListEventsRequest
	5,  // 14: event.v1.EventService.UpdateEvent:input_type -> event.v1.UpdateEventRequest
	6,  // 15: event.v1.EventService.DeleteEvent:input_type -> event.v1.DeleteEventRequest
	10, // 16: event.v1.EventService.GetTicketAvailability:input_type -> event.v1.GetTicketAvailabilityRequest
	12, // 17: event.v1.EventService.UpdateTicketAvailability:input_type -> event.v1.UpdateTicketAvailabilityRequest
	12, // 18: event.v1.EventService.UpdateBatchTicketAvailability:input_type -> event.v1.UpdateTicketAvailabilityRequest
	14, // 19: event.v1.EventService.GetSeats:input_type -> event.v1.GetSeatsRequest
	16, // 20: event.v1.EventService.UpdateSeatStatus:input_type -> event.v1.UpdateSeatStatusRequest
	17, // 21: event.v1.EventService.UpdateBatchSeatStatus:input_type -> event.v1.UpdateBatchSeatStatusRequest
	8,  // 22: event.v1.EventService.CreateEvent:output_type -> event.v1.EventDetail
	8,  // 23: event.v1.EventService.GetEvent:output_type -> event.v1.EventDetail
	4,  // 24: event.v1.EventService.ListEvents:output_type -> event.v1.ListEventsResponse
	8,  // 25: event.v1.EventService.UpdateEvent:output_type -> event.v1.EventDetail
	7,  // 26: event.v1.EventService.DeleteEvent:output_type -> event.v1.DeleteEventResponse
	11, // 27: event.v1.EventService.GetTicketAvailability:output_type -> event.v1.TicketAvailabilityResponse
	9,  // 28: event.v1.EventService.UpdateTicketAvailability:output_type -> event.v1.TicketTier
	20, // 29: event.v1.EventService.UpdateBatchTicketAvailability:output_type -> google.protobuf.Empty
	15, // 30: event.v1.EventService.GetSeats:output_type -> event.v1.GetSeatsResponse
	18, // 31: event.v1.EventService.UpdateSeatStatus:output_type -> event.v1.UpdateSeatStatusResponse
	20, // 32: event.v1.EventService.UpdateBatchSeatStatus:output_type -> google.protobuf.Empty
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_event_v1_event_proto_init() }
func file_proto_event_v1_event_proto_init() {
	if File_proto_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_v1_event_proto_rawDesc), len(file_proto_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_v1_event_proto_goTypes,
		DependencyIndexes: file_proto_event_v1_event_proto_depIdxs,
		MessageInfos:      file_proto_event_v1_event_proto_msgTypes,
	}.Build()
	File_proto_event_v1_event_proto = out.File
	file_proto_event_v1_event_proto_goTypes = nil
	file_proto_event_v1_event_proto_depIdxs = nil
}
