package saga

type SagaStepName string

const (
	UNDO_CREATE_BOOKING_STEP   SagaStepName = "UNDO_CREATE_BOOKING_STEP"
	RESERVED_SEAT_STEP         SagaStepName = "RESERVED_SEAT_STEP"
	UNDO_RESERVED_SEAT_STEP    SagaStepName = "UNDO_RESERVED_SEAT_STEP"
	CREATE_PAYMENT_INTENT_STEP SagaStepName = "CREATE_PAYMENT_INTENT_STEP"
	// Refund
	UNDO_PAYMENT_INTENT_STEP               SagaStepName = "UNDO_PAYMENT_INTENT_STEP"
	CREATE_ORDER_RECORD_STEP               SagaStepName = "CREATE_ORDER_RECORD_STEP"
	UNDO_CREATE_ORDER_RECORD_STEP          SagaStepName = "UNDO_CREATE_ORDER_RECORD_STEP"
	UPDATE_BOOKING_STATUS_STEP             SagaStepName = "UPDATE_BOOKING_STATUS_STEP"
	SEND_BOOKING_SUCCESS_NOTIFICATION_STEP SagaStepName = "UPDATE_BOOKING_STATUS_STEP"
)
