package saga

type SagaStepName string

const (
	RESERVED_SEAT_STEP         SagaStepName = "RESERVED_SEAT_STEP"
	CREATE_PAYMENT_INTENT_STEP SagaStepName = "CREATE_PAYMENT_INTENT_STEP"
	// Refund
	// UNDO_PAYMENT_INTENT_STEP               SagaStepName = "UNDO_PAYMENT_INTENT_STEP"
	// CREATE_ORDER_RECORD_STEP               SagaStepName = "CREATE_ORDER_RECORD_STEP"
	// UNDO_CREATE_ORDER_RECORD_STEP          SagaStepName = "UNDO_CREATE_ORDER_RECORD_STEP"
	// UPDATE_BOOKING_STATUS_STEP             SagaStepName = "UPDATE_BOOKING_STATUS_STEP"
	// SEND_BOOKING_SUCCESS_NOTIFICATION_STEP SagaStepName = "UPDATE_BOOKING_STATUS_STEP"

	UPDATE_SEAT_BOOKED              SagaStepName = "UPDATE_SEAT_BOOKED"
	UPDATE_BOOKING_STATUS_CONFIRMED SagaStepName = "UPDATE_BOOKING_STATUS_CONFIRMED"
)
