// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdReq) Reset() {
	*x = GetPaymentByIdReq{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdReq) ProtoMessage() {}

func (x *GetPaymentByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdReq.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PaymentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	TransactionId string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,9,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentEntry) Reset() {
	*x = PaymentEntry{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEntry) ProtoMessage() {}

func (x *PaymentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEntry.ProtoReflect.Descriptor instead.
func (*PaymentEntry) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentEntry) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *PaymentEntry) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentEntry) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PaymentEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentEntry) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UserEmail     string                 `protobuf:"bytes,6,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreatePaymentRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type CreatePaymentResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status                    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentIntentId           string                 `protobuf:"bytes,3,opt,name=paymentIntentId,proto3" json:"paymentIntentId,omitempty"`
	PaymentIntentClientSecret string                 `protobuf:"bytes,4,opt,name=paymentIntentClientSecret,proto3" json:"paymentIntentClientSecret,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentIntentClientSecret() string {
	if x != nil {
		return x.PaymentIntentClientSecret
	}
	return ""
}

type GetPaymentsReqeust struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsReqeust) Reset() {
	*x = GetPaymentsReqeust{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsReqeust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsReqeust) ProtoMessage() {}

func (x *GetPaymentsReqeust) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsReqeust.ProtoReflect.Descriptor instead.
func (*GetPaymentsReqeust) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentsReqeust) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPaymentsReqeust) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentsReqeust) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *GetPaymentsReqeust) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetPaymentsReqeust) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPaymentsReqeust) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type PaymentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentEntry        `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentList) Reset() {
	*x = PaymentList{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentList) ProtoMessage() {}

func (x *PaymentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentList.ProtoReflect.Descriptor instead.
func (*PaymentList) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentList) GetPayments() []*PaymentEntry {
	if x != nil {
		return x.Payments
	}
	return nil
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePaymentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdatePaymentStatusByPaymentIntentIdReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=paymentIntentId,proto3" json:"paymentIntentId,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePaymentStatusByPaymentIntentIdReq) Reset() {
	*x = UpdatePaymentStatusByPaymentIntentIdReq{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusByPaymentIntentIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusByPaymentIntentIdReq) ProtoMessage() {}

func (x *UpdatePaymentStatusByPaymentIntentIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusByPaymentIntentIdReq.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusByPaymentIntentIdReq) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePaymentStatusByPaymentIntentIdReq) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *UpdatePaymentStatusByPaymentIntentIdReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdatePaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdatePaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeletePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRequest) Reset() {
	*x = DeletePaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRequest) ProtoMessage() {}

func (x *DeletePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetPaymentByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xff\x02\n" +
	"\fPaymentEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x12%\n" +
	"\x0epayment_method\x18\t \x01(\tR\rpaymentMethod\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc6\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"user_email\x18\x06 \x01(\tR\tuserEmail\"\xa7\x01\n" +
	"\x15CreatePaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x0fpaymentIntentId\x18\x03 \x01(\tR\x0fpaymentIntentId\x12<\n" +
	"\x19paymentIntentClientSecret\x18\x04 \x01(\tR\x19paymentIntentClientSecret\"\xbd\x01\n" +
	"\x12GetPaymentsReqeust\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\"C\n" +
	"\vPaymentList\x124\n" +
	"\bpayments\x18\x01 \x03(\v2\x18.payment.v1.PaymentEntryR\bpayments\"D\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"k\n" +
	"'UpdatePaymentStatusByPaymentIntentIdReq\x12(\n" +
	"\x0fpaymentIntentId\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x80\x01\n" +
	"\x14UpdatePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"&\n" +
	"\x14DeletePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xdb\x04\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12I\n" +
	"\x0eGetPaymentById\x12\x1d.payment.v1.GetPaymentByIdReq\x1a\x18.payment.v1.PaymentEntry\x12F\n" +
	"\vGetPayments\x12\x1e.payment.v1.GetPaymentsReqeust\x1a\x17.payment.v1.PaymentList\x12U\n" +
	"\x13UpdatePaymentStatus\x12&.payment.v1.UpdatePaymentStatusRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rUpdatePayment\x12 .payment.v1.UpdatePaymentRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rDeletePayment\x12 .payment.v1.DeletePaymentRequest\x1a\x16.google.protobuf.Empty\x12s\n" +
	"$UpdatePaymentStatusByPaymentIntentId\x123.payment.v1.UpdatePaymentStatusByPaymentIntentIdReq\x1a\x16.google.protobuf.EmptyB5Z3github.com/ticketbox/pkg/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_proto_rawDescData
}

var file_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_payment_v1_payment_proto_goTypes = []any{
	(*GetPaymentByIdReq)(nil),                       // 0: payment.v1.GetPaymentByIdReq
	(*PaymentEntry)(nil),                            // 1: payment.v1.PaymentEntry
	(*CreatePaymentRequest)(nil),                    // 2: payment.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),                   // 3: payment.v1.CreatePaymentResponse
	(*GetPaymentsReqeust)(nil),                      // 4: payment.v1.GetPaymentsReqeust
	(*PaymentList)(nil),                             // 5: payment.v1.PaymentList
	(*UpdatePaymentStatusRequest)(nil),              // 6: payment.v1.UpdatePaymentStatusRequest
	(*UpdatePaymentStatusByPaymentIntentIdReq)(nil), // 7: payment.v1.UpdatePaymentStatusByPaymentIntentIdReq
	(*UpdatePaymentRequest)(nil),                    // 8: payment.v1.UpdatePaymentRequest
	(*DeletePaymentRequest)(nil),                    // 9: payment.v1.DeletePaymentRequest
	(*timestamppb.Timestamp)(nil),                   // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                           // 11: google.protobuf.Empty
}
var file_proto_payment_v1_payment_proto_depIdxs = []int32{
	10, // 0: payment.v1.PaymentEntry.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: payment.v1.PaymentEntry.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: payment.v1.PaymentList.payments:type_name -> payment.v1.PaymentEntry
	2,  // 3: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	0,  // 4: payment.v1.PaymentService.GetPaymentById:input_type -> payment.v1.GetPaymentByIdReq
	4,  // 5: payment.v1.PaymentService.GetPayments:input_type -> payment.v1.GetPaymentsReqeust
	6,  // 6: payment.v1.PaymentService.UpdatePaymentStatus:input_type -> payment.v1.UpdatePaymentStatusRequest
	8,  // 7: payment.v1.PaymentService.UpdatePayment:input_type -> payment.v1.UpdatePaymentRequest
	9,  // 8: payment.v1.PaymentService.DeletePayment:input_type -> payment.v1.DeletePaymentRequest
	7,  // 9: payment.v1.PaymentService.UpdatePaymentStatusByPaymentIntentId:input_type -> payment.v1.UpdatePaymentStatusByPaymentIntentIdReq
	3,  // 10: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	1,  // 11: payment.v1.PaymentService.GetPaymentById:output_type -> payment.v1.PaymentEntry
	5,  // 12: payment.v1.PaymentService.GetPayments:output_type -> payment.v1.PaymentList
	11, // 13: payment.v1.PaymentService.UpdatePaymentStatus:output_type -> google.protobuf.Empty
	11, // 14: payment.v1.PaymentService.UpdatePayment:output_type -> google.protobuf.Empty
	11, // 15: payment.v1.PaymentService.DeletePayment:output_type -> google.protobuf.Empty
	11, // 16: payment.v1.PaymentService.UpdatePaymentStatusByPaymentIntentId:output_type -> google.protobuf.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_proto_init() }
func file_proto_payment_v1_payment_proto_init() {
	if File_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_proto = out.File
	file_proto_payment_v1_payment_proto_goTypes = nil
	file_proto_payment_v1_payment_proto_depIdxs = nil
}
