// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/scheduler/v1/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateSchedulerByIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsEnable       bool                   `protobuf:"varint,2,opt,name=is_enable,json=isEnable,proto3" json:"is_enable,omitempty"`
	CronExpression string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSchedulerByIdRequest) Reset() {
	*x = UpdateSchedulerByIdRequest{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchedulerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchedulerByIdRequest) ProtoMessage() {}

func (x *UpdateSchedulerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchedulerByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateSchedulerByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateSchedulerByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSchedulerByIdRequest) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

func (x *UpdateSchedulerByIdRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

type ListActiveSchedulersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSchedulersRequest) Reset() {
	*x = ListActiveSchedulersRequest{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSchedulersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSchedulersRequest) ProtoMessage() {}

func (x *ListActiveSchedulersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSchedulersRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSchedulersRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

type ListActiveSchedulersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedulers    []*SchedulerItem       `protobuf:"bytes,1,rep,name=schedulers,proto3" json:"schedulers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSchedulersResponse) Reset() {
	*x = ListActiveSchedulersResponse{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSchedulersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSchedulersResponse) ProtoMessage() {}

func (x *ListActiveSchedulersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSchedulersResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSchedulersResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ListActiveSchedulersResponse) GetSchedulers() []*SchedulerItem {
	if x != nil {
		return x.Schedulers
	}
	return nil
}

type SchedulerItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CronExpression string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	IsEnabled      bool                   `protobuf:"varint,4,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	Version        int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Timeout        int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulerItem) Reset() {
	*x = SchedulerItem{}
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerItem) ProtoMessage() {}

func (x *SchedulerItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerItem.ProtoReflect.Descriptor instead.
func (*SchedulerItem) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *SchedulerItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SchedulerItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchedulerItem) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *SchedulerItem) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *SchedulerItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SchedulerItem) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SchedulerItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SchedulerItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\"proto/scheduler/v1/scheduler.proto\x12\fscheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"r\n" +
	"\x1aUpdateSchedulerByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tis_enable\x18\x02 \x01(\bR\bisEnable\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\"\x1d\n" +
	"\x1bListActiveSchedulersRequest\"[\n" +
	"\x1cListActiveSchedulersResponse\x12;\n" +
	"\n" +
	"schedulers\x18\x01 \x03(\v2\x1b.scheduler.v1.SchedulerItemR\n" +
	"schedulers\"\xa5\x02\n" +
	"\rSchedulerItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x04 \x01(\bR\tisEnabled\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xda\x01\n" +
	"\x10SchedulerService\x12m\n" +
	"\x14ListActiveSchedulers\x12).scheduler.v1.ListActiveSchedulersRequest\x1a*.scheduler.v1.ListActiveSchedulersResponse\x12W\n" +
	"\x13UpdateSchedulerById\x12(.scheduler.v1.UpdateSchedulerByIdRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/ticketbox/pkg/proto/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_proto_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_v1_scheduler_proto_rawDesc), len(file_proto_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_v1_scheduler_proto_rawDescData
}

var file_proto_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scheduler_v1_scheduler_proto_goTypes = []any{
	(*UpdateSchedulerByIdRequest)(nil),   // 0: scheduler.v1.UpdateSchedulerByIdRequest
	(*ListActiveSchedulersRequest)(nil),  // 1: scheduler.v1.ListActiveSchedulersRequest
	(*ListActiveSchedulersResponse)(nil), // 2: scheduler.v1.ListActiveSchedulersResponse
	(*SchedulerItem)(nil),                // 3: scheduler.v1.SchedulerItem
	(*timestamppb.Timestamp)(nil),        // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 5: google.protobuf.Empty
}
var file_proto_scheduler_v1_scheduler_proto_depIdxs = []int32{
	3, // 0: scheduler.v1.ListActiveSchedulersResponse.schedulers:type_name -> scheduler.v1.SchedulerItem
	4, // 1: scheduler.v1.SchedulerItem.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: scheduler.v1.SchedulerItem.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: scheduler.v1.SchedulerService.ListActiveSchedulers:input_type -> scheduler.v1.ListActiveSchedulersRequest
	0, // 4: scheduler.v1.SchedulerService.UpdateSchedulerById:input_type -> scheduler.v1.UpdateSchedulerByIdRequest
	2, // 5: scheduler.v1.SchedulerService.ListActiveSchedulers:output_type -> scheduler.v1.ListActiveSchedulersResponse
	5, // 6: scheduler.v1.SchedulerService.UpdateSchedulerById:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_scheduler_v1_scheduler_proto_init() }
func file_proto_scheduler_v1_scheduler_proto_init() {
	if File_proto_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_v1_scheduler_proto_rawDesc), len(file_proto_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_v1_scheduler_proto = out.File
	file_proto_scheduler_v1_scheduler_proto_goTypes = nil
	file_proto_scheduler_v1_scheduler_proto_depIdxs = nil
}
